In [1]:
import pandas as pd

In [2]:
pip install yfinance --upgrade --no-cache-dir

Requirement already satisfied: yfinance in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (0.2.40)
Requirement already satisfied: pandas>=1.3.0 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (2.0.0)
Requirement already satisfied: requests>=2.31 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (2.32.3)
Requirement already satisfied: multitasking>=0.0.7 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (0.0.11)
Requirement already satisfied: lxml>=4.9.1 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (5.2.2)
Requirement already satisfied: platformdirs>=2.0.0 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (4.2.2)
Requirement already satisfied: pytz>=2022.5 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (2024.1)
Requirement already satisfied: frozendict>=2.3.4 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (2.4.4)
Requirement already satisfied: peewee>=3.16.2 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (3.17.6)
Requirement already satisfied: beautifulsoup4>=4.11.1 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (4.12.3)
Requirement already satisfied: html5lib>=1.1 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from yfinance) (1.1)
Requirement already satisfied: soupsieve>1.2 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from beautifulsoup4>=4.11.1->yfinance) (2.5)
Requirement already satisfied: six>=1.9 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from html5lib>=1.1->yfinance) (1.16.0)
Requirement already satisfied: webencodings in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from html5lib>=1.1->yfinance) (0.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from pandas>=1.3.0->yfinance) (2024.1)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from requests>=2.31->yfinance) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from requests>=2.31->yfinance) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from requests>=2.31->yfinance) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\marci\onedrive\desktop\fiap\dev\yfinance\venv\lib\site-packages (from requests>=2.31->yfinance) (2024.7.4)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 24.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import yfinance as yf

In [4]:
msft = yf.Ticker("MSFT")
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 56,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 9276400,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 64,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 3591277,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 51,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 3452196,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 49,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1974,
   'fiscalYear': 2023,
   'totalPay': 3355797,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 51,
   'title': 'Executive Vice President of Business Development, Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 2460507,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 56,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 51,
   'title': 'Executive VP of AI & CTO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Chief Communications Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 3,
 'boardRisk': 4,
 'compensationRisk': 2,
 'shareHolderRightsRisk': 2,
 'overallRisk': 1,
 'governanceEpochDate': 1719792000,
 'compensationAsOfEpochDate': 1703980800,
 'irWebsite': 'http://www.microsoft.com/investor/default.aspx',
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 460.77,
 'open': 459.66,
 'dayLow': 458.965,
 'dayHigh': 468.35,
 'regularMarketPreviousClose': 460.77,
 'regularMarketOpen': 459.66,
 'regularMarketDayLow': 458.965,
 'regularMarketDayHigh': 468.35,
 'dividendRate': 3.0,
 'dividendYield': 0.0064,
 'exDividendDate': 1723680000,
 'payoutRatio': 0.24780001,
 'fiveYearAvgDividendYield': 0.92,
 'beta': 0.894,
 'trailingPE': 40.481384,
 'forwardPE': 35.15489,
 'volume': 15662166,
 'regularMarketVolume': 15662166,
 'averageVolume': 18836435,
 'averageVolume10days': 18437860,
 'averageDailyVolume10Day': 18437860,
 'bid': 467.3,
 'ask': 467.52,
 'bidSize': 100,
 'askSize': 200,
 'marketCap': 3475050856448,
 'fiftyTwoWeekLow': 309.45,
 'fiftyTwoWeekHigh': 468.35,
 'priceToSalesTrailing12Months': 14.688444,
 'fiftyDayAverage': 427.2934,
 'twoHundredDayAverage': 392.13004,
 'trailingAnnualDividendRate': 2.93,
 'trailingAnnualDividendYield': 0.006358921,
 'currency': 'USD',
 'enterpriseValue': 3501264994304,
 'profitMargins': 0.36426997,
 'floatShares': 7422123535,
 'sharesOutstanding': 7432309760,
 'sharesShort': 62396959,
 'sharesShortPriorMonth': 43764126,
 'sharesShortPreviousMonthDate': 1715731200,
 'dateShortInterest': 1718323200,
 'sharesPercentSharesOut': 0.0084,
 'heldPercentInsiders': 0.00054000004,
 'heldPercentInstitutions': 0.73635,
 'shortRatio': 3.41,
 'shortPercentOfFloat': 0.0084,
 'impliedSharesOutstanding': 7432309760,
 'bookValue': 34.058,
 'priceToBook': 13.728346,
 'lastFiscalYearEnd': 1688083200,
 'nextFiscalYearEnd': 1719705600,
 'mostRecentQuarter': 1711843200,
 'earningsQuarterlyGrowth': 0.199,
 'netIncomeToCommon': 86181003264,
 'trailingEps': 11.55,
 'forwardEps': 13.3,
 'pegRatio': 2.4,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 14.799,
 'enterpriseToEbitda': 27.792,
 '52WeekChange': 0.40903473,
 'SandP52WeekChange': 0.26253593,
 'lastDividendValue': 0.75,
 'lastDividendDate': 1715731200,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EDT',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -14400000,
 'currentPrice': 467.56,
 'targetHighPrice': 600.0,
 'targetLowPrice': 436.0,
 'targetMeanPrice': 488.97,
 'targetMedianPrice': 480.89,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 46,
 'totalCash': 80013000704,
 'totalCashPerShare': 10.766,
 'ebitda': 125981999104,
 'totalDebt': 106228998144,
 'quickRatio': 1.132,
 'currentRatio': 1.242,
 'totalRevenue': 236583993344,
 'debtToEquity': 41.963,
 'revenuePerShare': 31.834,
 'returnOnAssets': 0.1541,
 'returnOnEquity': 0.38487998,
 'freeCashflow': 61997998080,
 'operatingCashflow': 110122999808,
 'earningsGrowth': 0.2,
 'revenueGrowth': 0.17,
 'grossMargins': 0.69894,
 'ebitdaMargins': 0.5325,
 'operatingMargins': 0.44588003,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.3053}

In [5]:
hist = msft.history(period="1mo")

In [6]:
hist

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-06 00:00:00-04:00,424.010010,425.309998,420.579987,424.519989,14861300,0.0,0.0
2024-06-07 00:00:00-04:00,426.200012,426.279999,423.000000,423.850006,13621700,0.0,0.0
2024-06-10 00:00:00-04:00,424.700012,428.079987,423.890015,427.869995,14003000,0.0,0.0
2024-06-11 00:00:00-04:00,425.480011,432.820007,425.250000,432.679993,14551100,0.0,0.0
2024-06-12 00:00:00-04:00,435.320007,443.399994,433.250000,441.059998,22366200,0.0,0.0
2024-06-13 00:00:00-04:00,440.850006,443.390015,439.369995,441.579987,15960600,0.0,0.0
2024-06-14 00:00:00-04:00,438.279999,443.140015,436.720001,442.570007,13582000,0.0,0.0
2024-06-17 00:00:00-04:00,442.589996,450.940002,440.720001,448.369995,20790000,0.0,0.0
2024-06-18 00:00:00-04:00,449.709991,450.140015,444.890015,446.339996,17112500,0.0,0.0
2024-06-20 00:00:00-04:00,446.299988,446.529999,441.269989,445.700012,19877400,0.0,0.0
2024-06-21 00:00:00-04:00,447.380005,450.579987,446.510010,449.779999,34486200,0.0,0.0
2024-06-24 00:00:00-04:00,449.799988,452.750000,446.410004,447.670013,15913700,0.0,0.0
2024-06-25 00:00:00-04:00,448.250000,451.420013,446.750000,450.950012,16747500,0.0,0.0
2024-06-26 00:00:00-04:00,449.000000,453.600006,448.190002,452.160004,16507000,0.0,0.0
2024-06-27 00:00:00-04:00,452.179993,456.170013,451.769989,452.850006,14806300,0.0,0.0
2024-06-28 00:00:00-04:00,453.070007,455.380005,446.410004,446.950012,28362300,0.0,0.0
2024-07-01 00:00:00-04:00,448.660004,457.369995,445.660004,456.730011,17662800,0.0,0.0
2024-07-02 00:00:00-04:00,453.200012,459.589996,453.109985,459.279999,13979800,0.0,0.0
2024-07-03 00:00:00-04:00,458.190002,461.019989,457.880005,460.769989,9932800,0.0,0.0
2024-07-05 00:00:00-04:00,459.609985,468.350006,458.970001,467.559998,15980200,0.0,0.0

In [7]:
msft.history_metadata

{'currency': 'USD',
 'symbol': 'MSFT',
 'exchangeName': 'NMS',
 'fullExchangeName': 'NasdaqGS',
 'instrumentType': 'EQUITY',
 'firstTradeDate': 511108200,
 'regularMarketTime': 1720209601,
 'hasPrePostMarketData': True,
 'gmtoffset': -14400,
 'timezone': 'EDT',
 'exchangeTimezoneName': 'America/New_York',
 'regularMarketPrice': 467.56,
 'fiftyTwoWeekHigh': 468.35,
 'fiftyTwoWeekLow': 458.965,
 'regularMarketDayHigh': 468.35,
 'regularMarketDayLow': 458.965,
 'regularMarketVolume': 15662166,
 'chartPreviousClose': 424.01,
 'priceHint': 2,
 'currentTradingPeriod': {'pre': {'timezone': 'EDT',
   'start': 1720166400,
   'end': 1720186200,
   'gmtoffset': -14400},
  'regular': {'timezone': 'EDT',
   'start': 1720186200,
   'end': 1720209600,
   'gmtoffset': -14400},
  'post': {'timezone': 'EDT',
   'start': 1720209600,
   'end': 1720224000,
   'gmtoffset': -14400}},
 'dataGranularity': '1d',
 'range': '1mo',
 'validRanges': ['1d',
  '5d',
  '1mo',
  '3mo',
  '6mo',
  '1y',
  '2y',
  '5y',
  '10y',
  'ytd',
  'max']}

In [8]:
msft.actions

Empty DataFrame
Columns: [Dividends, Stock Splits]
Index: []

In [9]:
msft.dividends

Series([], Name: Dividends, dtype: float64)

In [10]:
msft.splits

Series([], Name: Stock Splits, dtype: float64)

In [11]:
tickers = yf.Tickers('msft aapl goog')

In [12]:
import os

In [23]:
df = tickers.tickers['MSFT'].history(period = '5d')
df = pd.DataFrame(df)
df

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-06-28 00:00:00-04:00,453.070007,455.380005,446.410004,446.950012,28362300,0.0,0.0
2024-07-01 00:00:00-04:00,448.660004,457.369995,445.660004,456.730011,17662800,0.0,0.0
2024-07-02 00:00:00-04:00,453.200012,459.589996,453.109985,459.279999,13979800,0.0,0.0
2024-07-03 00:00:00-04:00,458.190002,461.019989,457.880005,460.769989,9932800,0.0,0.0
2024-07-05 00:00:00-04:00,459.609985,468.350006,458.970001,467.559998,15980200,0.0,0.0

In [39]:
import math
import numpy as np

In [57]:
df = df[['Open','High','Low','Close','Volume']]

In [70]:
df['Amplitude_de_preco'] = abs(df['High'] - df['Low'])
df['Volume'] = np.float64(df['Volume'])
df['Total_RS_negociado'] = df['Volume'] * df['Close']

In [71]:
df

,Open,High,Low,Close,Volume,Amplitude_de_preco,Total_RS_negociado
Date,,,,,,,
2024-06-28 00:00:00-04:00,453.070007,455.380005,446.410004,446.950012,28362300.0,8.970001,1.267653e+10
2024-07-01 00:00:00-04:00,448.660004,457.369995,445.660004,456.730011,17662800.0,11.709991,8.067131e+09
2024-07-02 00:00:00-04:00,453.200012,459.589996,453.109985,459.279999,13979800.0,6.480011,6.420643e+09
2024-07-03 00:00:00-04:00,458.190002,461.019989,457.880005,460.769989,9932800.0,3.139984,4.576736e+09
2024-07-05 00:00:00-04:00,459.609985,468.350006,458.970001,467.559998,15980200.0,9.380005,7.471702e+09

In [98]:
root = f"C:\\Users\\marci\\OneDrive\\Desktop\\FIAP\\dev\\yfinance"

In [99]:
from datetime import date

str_date = date.today().strftime("%Y/%m/%d").replace('/','')
str_date

'20240706'

In [101]:
today_path = os.path.join(root, str_date)
os.path.exists(today_path)

False

'C:\\Users\\marci\\OneDrive\\Desktop\\FIAP\\dev'